# steps:
#   - name: "gcr.io/cloud-builders/npm"
#     args: ["ci"]
#   - name: "gcr.io/cloud-builders/npm"
#     args: ["run", "build"]
#   - name: "gcr.io/cloud-builders/gcloud"
#     args: ["app", "deploy", "--quiet"]

# timeout: "900s"

# options:
#   logging: CLOUD_LOGGING_ONLY
#   default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hello-world-1", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/hello-world-1"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - hello-world-1
      - --image=gcr.io/$PROJECT_ID/hello-world-1
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

timeout: "900s"

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

