# steps:
#   - name: "gcr.io/cloud-builders/npm"
#     args: ["ci"]
#   - name: "gcr.io/cloud-builders/npm"
#     args: ["run", "build"]
#   - name: "gcr.io/cloud-builders/gcloud"
#     args: ["app", "deploy", "--quiet"]

# timeout: "900s"

# options:
#   logging: CLOUD_LOGGING_ONLY
#   default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
steps:
  # Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]

  # Build your TypeScript backend
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]

  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/YOUR_SERVICE_NAME", "."]

  # Push Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/YOUR_SERVICE_NAME"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - YOUR_SERVICE_NAME
      - --image=gcr.io/$PROJECT_ID/YOUR_SERVICE_NAME
      - --region=YOUR_REGION
      - --platform=managed
      - --allow-unauthenticated

timeout: "900s"

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
